---
builds:
- binary: ci-info
  main: cmd/ci-info/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
release:
  # We update release page manually before releasing
  # So make prerelease true
  prerelease: true
